platform :ios, '9.0'
use_frameworks!

target 'NixCamera_Example' do
  pod 'NixCamera', :path => '../'
  pod 'CircleProgressView'
  pod 'Masonry'
  pod 'RFRotate'
  target 'NixCamera_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'CircleProgressView'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
        if target.name == 'FBSnapshotTestCase'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
