use_frameworks!

target 'NixCamera_Example' do
  pod 'NixCamera', :path => '../'
  use_frameworks!
  pod 'CircleProgressView'
  
  target 'NixCamera_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
    pod 'FBSnapshotTestCase'
  end
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == '<insert target name of your pod here>'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
